"""changelog 21092023

Revision ID: 21f9b7595174
Revises: 4395275559b3
Create Date: 2023-09-21 21:25:04.657415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f9b7595174'
down_revision = '4395275559b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
