"""empty message

Revision ID: 2ca976493d71
Revises: dedd1c83a6db
Create Date: 2023-02-06 20:33:08.544439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ca976493d71'
down_revision = 'dedd1c83a6db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_data', sa.Column('flow_rate', sa.Float(), nullable=True))
    op.drop_column('flow_data', 'flow')
    op.add_column('pumps', sa.Column('current', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'pumps', ['pump_id'])
    op.alter_column('sensors', 'set_lvl_1',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sensors', 'set_lvl_2',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sensors', 'set_lvl_3',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'sensors', ['sensor_id'])
    op.add_column('shifts', sa.Column('Mon', sa.Boolean(), nullable=True))
    op.add_column('shifts', sa.Column('Tue', sa.Boolean(), nullable=True))
    op.add_column('shifts', sa.Column('Wed', sa.Boolean(), nullable=True))
    op.add_column('shifts', sa.Column('Thu', sa.Boolean(), nullable=True))
    op.add_column('shifts', sa.Column('Fri', sa.Boolean(), nullable=True))
    op.add_column('shifts', sa.Column('Sat', sa.Boolean(), nullable=True))
    op.add_column('shifts', sa.Column('Sun', sa.Boolean(), nullable=True))
    op.drop_column('shifts', 'thu')
    op.drop_column('shifts', 'wed')
    op.drop_column('shifts', 'sun')
    op.drop_column('shifts', 'tue')
    op.drop_column('shifts', 'mon')
    op.drop_column('shifts', 'fri')
    op.drop_column('shifts', 'sat')
    op.create_unique_constraint(None, 'subscriptions', ['mail'])
    op.create_unique_constraint(None, 'valves', ['valve_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'valves', type_='unique')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.add_column('shifts', sa.Column('sat', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('fri', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('mon', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('tue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('sun', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('wed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('thu', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('shifts', 'Sun')
    op.drop_column('shifts', 'Sat')
    op.drop_column('shifts', 'Fri')
    op.drop_column('shifts', 'Thu')
    op.drop_column('shifts', 'Wed')
    op.drop_column('shifts', 'Tue')
    op.drop_column('shifts', 'Mon')
    op.drop_constraint(None, 'sensors', type_='unique')
    op.alter_column('sensors', 'set_lvl_3',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sensors', 'set_lvl_2',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sensors', 'set_lvl_1',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'pumps', type_='unique')
    op.drop_column('pumps', 'current')
    op.add_column('flow_data', sa.Column('flow', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('flow_data', 'flow_rate')
    # ### end Alembic commands ###
