"""add shift sections

Revision ID: 3b88f2a7c5d7
Revises: 62e99ce84147
Create Date: 2023-09-05 15:39:46.337687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b88f2a7c5d7'
down_revision = '62e99ce84147'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('shift_id', sa.Integer(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['shift_id'], ['shifts.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ###op.drop_table('spatial_ref_sys')### #
    op.add_column('sensors', sa.Column(
        'section_id', sa.Integer(), nullable=True))
    op.drop_column('sensors', 'shift_id')
    op.add_column('valves', sa.Column(
        'section_id', sa.Integer(), nullable=True))
    op.drop_column('valves', 'shift_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valves', sa.Column('shift_id', sa.INTEGER(),
                  autoincrement=False, nullable=True))
    op.drop_column('valves', 'section_id')
    op.add_column('sensors', sa.Column('shift_id', sa.INTEGER(),
                  autoincrement=False, nullable=True))
    op.drop_column('sensors', 'section_id')
    op.create_table('spatial_ref_sys',
                    sa.Column('srid', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('auth_name', sa.VARCHAR(length=256),
                              autoincrement=False, nullable=True),
                    sa.Column('auth_srid', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('srtext', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.Column('proj4text', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)',
                                       name='spatial_ref_sys_srid_check'),
                    sa.PrimaryKeyConstraint(
                        'srid', name='spatial_ref_sys_pkey')
                    )
    op.drop_table('sections')
    # ### end Alembic commands ###
