"""cascade delete all

Revision ID: 3bc8ca169278
Revises: b5b69f9c8284
Create Date: 2023-09-29 18:10:33.253731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc8ca169278'
down_revision = 'b5b69f9c8284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flow_data_pump_id_fkey', 'flow_data', type_='foreignkey')
    op.create_foreign_key(None, 'flow_data', 'pumps', ['pump_id'], ['pump_id'], ondelete='CASCADE')
    op.drop_constraint('notifications_user_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user'], ['username'], ondelete='CASCADE')
    op.drop_constraint('sensor_data_sensor_id_fkey', 'sensor_data', type_='foreignkey')
    op.create_foreign_key(None, 'sensor_data', 'sensors', ['sensor_id'], ['sensor_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_data', type_='foreignkey')
    op.create_foreign_key('sensor_data_sensor_id_fkey', 'sensor_data', 'sensors', ['sensor_id'], ['sensor_id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_fkey', 'notifications', 'users', ['user'], ['username'])
    op.drop_constraint(None, 'flow_data', type_='foreignkey')
    op.create_foreign_key('flow_data_pump_id_fkey', 'flow_data', 'pumps', ['pump_id'], ['pump_id'])
    # ### end Alembic commands ###
