"""empty message

Revision ID: 3c5bf03fe1e2
Revises: c7d8b32d8527
Create Date: 2023-01-23 20:55:53.780284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5bf03fe1e2'
down_revision = 'c7d8b32d8527'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
