"""empty message

Revision ID: 62e99ce84147
Revises: 8c32bf32d804
Create Date: 2023-04-13 10:28:22.642619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e99ce84147'
down_revision = '8c32bf32d804'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'users', ['secret'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'secret')
    # ### end Alembic commands ###
