"""empty message

Revision ID: 8c32bf32d804
Revises: 2ca976493d71
Create Date: 2023-02-09 14:59:43.628023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c32bf32d804'
down_revision = '2ca976493d71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('disable', sa.Boolean(), nullable=True))
    op.drop_constraint('sensors_shift_id_fkey', 'sensors', type_='foreignkey')
    op.drop_constraint('valves_shift_id_fkey', 'valves', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('valves_shift_id_fkey', 'valves', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('sensors_shift_id_fkey', 'sensors', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.drop_column('logs', 'disable')
    # ### end Alembic commands ###
