"""added systemID str

Revision ID: b5b69f9c8284
Revises: 21f9b7595174
Create Date: 2023-09-22 21:17:51.771997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b69f9c8284'
down_revision = '21f9b7595174'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('systemID', sa.String(length=25), nullable=False))
    op.create_unique_constraint(None, 'systems', ['systemID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'systems', type_='unique')
    op.drop_column('systems', 'systemID')
    # ### end Alembic commands ###
